[build]
buildCommand = "npm install && npm run build"

[deploy]
preDeployCommand = ["/bin/sh -c \"python manage.py collectstatic --noinput\""]
startCommand     = "/bin/sh -c \"gunicorn backend.wsgi\""